# Setup
title:               Data science projects
tagline:             nana.ngannguyen@gmail.com
description:         A repository to store all my projects.
url:                 "https://kaleynguyen.github.io"
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
